// ═══════════════════════════════════════════════════════════════════
//  EXPANSION PACK — konten ringan buat nambah total fitur ke ~1200
// ═══════════════════════════════════════════════════════════════════
//  Semua isi di bawah ini teks original (ditulis sendiri, bukan kutipan
//  langsung dari anime/manga/lagu manapun) — aman dari hak cipta.
//  Registrasinya (reg() loop) ada di commands/index.js, mirip pola
//  RAM_TIERS/VALID_SERVERS di lib/pterodactylReseller.js.
// ═══════════════════════════════════════════════════════════════════

export const SMILEYLINE = [
    'Kalau ragu, itu tandanya kamu belum coba yang terkuat dari dirimu.',
    'Jangan minta maaf karena terlalu kuat. Minta maaflah kalau kamu nggak pakai kekuatan itu buat hal yang benar.',
    'Dunia ini penuh batasan, tapi batasan cuma ada di kepala orang yang berhenti mikir.',
    'Aku nggak sedang sombong. Aku cuma jujur soal seberapa kuat aku.',
    'Guru yang baik bukan yang selalu ada, tapi yang bikin muridnya nggak butuh dia lagi.',
    'Santai aja. Kalau ini serius, udah selesai dari tadi.',
    'Kekuatan itu tanggung jawab, bukan trofi buat dipamerkan sembarangan.',
    'Aku lebih suka dibenci karena jujur daripada disukai karena bohong.',
    'Anak muda harusnya bebas milih masa depan mereka sendiri.',
    'Kalau kamu jatuh, jatuhlah ke arah yang bikin kamu belajar sesuatu.',
    'Aku nggak pernah lari dari masalah. Aku cuma milih waktu yang tepat buat hadepin.',
    'Ketakutan itu manusiawi. Tapi jangan biarkan itu yang mutusin langkahmu.',
    'Yang bikin seseorang kuat bukan cuma tenaga, tapi keberanian buat berdiri sendirian kalau perlu.',
    'Aku nggak butuh validasi orang buat tau seberapa berharga usahaku.',
    'Kalau kamu nungguin waktu yang sempurna, kamu bakal nunggu selamanya.',
    'Percaya diri itu bukan soal nggak pernah salah, tapi soal berani coba lagi.',
    'Aku selalu bilang ke murid-muridku: masa depan kalian, kalian yang pegang kendali.',
    'Nggak semua pertarungan harus dimenangkan dengan kekerasan.',
    'Orang kuat itu ngelindungin, bukan nge-bully yang lemah.',
    'Aku nggak sempurna, tapi aku selalu berusaha jadi yang terbaik buat orang di sekitarku.',
    'Kalau semua orang meragukanmu, jadikan itu alasan buat buktiin, bukan buat nyerah.',
    'Kadang cara terbaik buat menang adalah nggak perlu bertarung sama sekali.',
    'Aku suka orang yang jujur soal kelemahannya. Itu tandanya dia lagi berusaha jadi lebih baik.',
    'Jangan biarkan masa lalu nentuin siapa kamu hari ini.',
    'Kekuatan sejati itu waktu kamu tetap tenang di tengah kekacauan.',
    'Aku nggak peduli seberapa besar rintangannya, selama tujuannya benar, aku maju terus.',
    'Belajar itu bukan cuma soal menang, tapi soal ngerti kenapa kamu bisa kalah.',
    'Orang hebat itu bukan yang nggak pernah gagal, tapi yang bangkit lebih cepat dari jatuhnya.',
    'Aku selalu kasih kesempatan kedua buat orang yang beneran mau berubah.',
    'Jangan remehin kekuatan niat yang tulus.',
    'Aku nggak pernah maksa orang buat percaya sama aku. Aku cuma nunjukin lewat tindakan.',
    'Kalau kamu takut gagal, artinya kamu masih peduli sama hasilnya. Itu bagus.',
    'Aku lebih milih ngajarin murid buat berpikir sendiri daripada nyuruh mereka nurut aja.',
    'Kekuatan tanpa hati itu cuma kehancuran yang ditunda.',
    'Aku selalu percaya, generasi berikutnya bisa lebih baik dari kita kalau dikasih kesempatan.',
    'Nggak ada yang namanya terlalu telat buat mulai lagi.',
    'Aku nggak nyari musuh, tapi aku juga nggak lari kalau ada yang datang.',
    'Yang paling berbahaya itu bukan lawan yang kuat, tapi keraguan di kepala sendiri.',
    'Percaya diri boleh, sombong jangan, tapi jangan juga minder berlebihan.',
    'Di akhir hari, yang penting itu kamu udah coba yang terbaik yang kamu bisa.',
];

export const JJK_TRIVIA = [
    'Jujutsu Kaisen dibuat oleh mangaka Gege Akutami dan terbit di majalah Weekly Shonen Jump.',
    "Dunia Jujutsu Kaisen berputar di sekitar 'kutukan' yang lahir dari emosi negatif manusia seperti takut dan benci.",
    'Penyihir kutukan (jujutsu sorcerer) menggunakan energi kutukan mereka sendiri buat ngelawan kutukan.',
    'Beberapa penyihir kutukan di cerita ini digambarkan sebagai yang terkuat sepanjang sejarah dalam dunianya.',
    'Semakin ramai suatu tempat, semakin besar kemungkinan kutukan kuat muncul di sana.',
    'Cursed Technique tiap sorcerer biasanya unik, berkembang sesuai kepribadian mereka masing-masing.',
    "Domain Expansion adalah teknik tingkat tinggi yang bikin area sekitar penggunanya jadi 'dunia' sendiri.",
    'Jujutsu Kaisen naik daun besar berkat adaptasi anime yang diproduksi studio MAPPA.',
    'Ceritanya masuk genre dark fantasy, banyak elemen horor dibanding shonen kebanyakan.',
    'Sekolah jujutsu jadi tempat murid-murid belajar ngendaliin energi kutukan sekaligus bertarung.',
    'Sukuna dikenal luas sebagai salah satu kutukan paling kuat dan ditakuti di ceritanya.',
    'Yuji Itadori jadi tokoh sentral setelah kejadian yang mengubah hidupnya di awal cerita.',
    'Jujutsu Kaisen sering disebut fans punya salah satu antagonis paling karismatik di shonen modern.',
    'Elemen komedi cukup sering diselipin di tengah cerita yang temanya cukup gelap.',
    'Desain karakter Jujutsu Kaisen sering dipuji karena detail dan ekspresifnya.',
    'Popularitas serinya bikin banyak merchandise dan kolaborasi bermunculan di berbagai negara.',
    'Lagu opening anime-nya sempat rame dibahas dan disukai banyak penonton.',
    'Beberapa karakter punya latar belakang keluarga yang jadi bagian penting dari cerita mereka.',
    'Sistem kekuatannya unik karena nggak cuma soal siapa paling kuat, tapi juga strategi.',
    'Banyak momen pertarungan yang dianggap ikonik fans karena koreografi dan momen dramatisnya.',
    'Ceritanya juga ngangkat tema soal pilihan hidup, kehilangan, dan arti jadi kuat buat ngelindungin orang lain.',
    'Beberapa nama teknik terinspirasi dari istilah budaya dan kepercayaan Jepang.',
    'Fanbase Jujutsu Kaisen dikenal aktif bikin fan art dan diskusi teori di berbagai platform.',
    'Serinya juga punya beberapa movie/spesial yang memperluas cerita di luar arc utama.',
    'Guru-guru di sekolah jujutsu biasanya juga sorcerer aktif yang turun tangan kalau darurat.',
    'Desain mata jadi salah satu ciri visual yang sering bikin karakter di anime ini gampang dikenali.',
    'Beberapa cursed spirit di cerita ini terinspirasi dari benda atau makhluk sehari-hari.',
    'Genre shonen kayak ini biasanya nekenin pertumbuhan karakter lewat latihan keras.',
    'Sampai sekarang, Jujutsu Kaisen masih jadi judul yang paling banyak dibahas komunitas anime.',
    'Beberapa guru di sekolah jujutsu digambarkan santai di luar, tapi serius soal melindungi murid-muridnya.',
];

export const ANIME_FACTS = [
    'Studio Ghibli, didirikan Hayao Miyazaki dan Isao Takahata, jadi salah satu studio animasi paling dihormati dunia.',
    "Istilah 'anime' di Jepang sebenarnya dipakai buat nyebut semua jenis animasi, bukan cuma buatan Jepang.",
    'One Piece karya Eiichiro Oda jadi salah satu manga terlaris sepanjang masa.',
    'Dragon Ball karya Akira Toriyama punya pengaruh besar ke banyak anime shonen modern.',
    'Genre isekai (dunia lain) jadi salah satu tren paling populer di industri anime belakangan ini.',
    'Banyak anime awalnya diadaptasi dari manga atau light novel sebelum ditayangkan.',
    'Studio seperti MAPPA, Ufotable, dan Wit Studio dikenal karena animasi pertarungan yang detail.',
    'Budaya cosplay tumbuh besar berkat popularitas anime dan manga di seluruh dunia.',
    'Beberapa anime butuh waktu produksi bertahun-tahun sebelum akhirnya tayang ke publik.',
    'Format shonen biasanya menyasar remaja laki-laki dengan tema petualangan dan pertarungan.',
    'Format shojo lebih sering ngangkat tema drama dan romansa.',
    'Naruto karya Masashi Kishimoto jadi salah satu anime paling berpengaruh buat generasi 2000-an.',
    'Attack on Titan dikenal karena worldbuilding dan plot twist yang bikin penasaran.',
    'Banyak seiyuu (pengisi suara) Jepang juga punya karier nyanyi di samping profesi dubbing.',
    'Comic Market di Jepang jadi salah satu event terbesar buat komunitas penggemar manga.',
    'Beberapa anime dibuat ulang bertahun-tahun kemudian dengan animasi yang lebih modern.',
    'Warna rambut mencolok di karakter anime sering dipakai buat bantu penonton bedain karakter cepat.',
    'Opening dan ending song anime sering jadi hits tersendiri di tangga lagu Jepang.',
    'Studio animasi sering kerja sama dengan banyak freelancer buat proses produksinya.',
    'Genre slice of life fokus ke momen kehidupan sehari-hari tanpa konflik besar.',
    'Beberapa anime terkenal justru awalnya kurang populer waktu manga-nya baru terbit.',
    'Platform streaming bikin anime makin gampang diakses penonton di luar Jepang.',
    'Anime action modern makin sering pakai CGI buat adegan pertarungan yang kompleks.',
    'Fandom anime di Indonesia termasuk salah satu yang paling aktif di Asia Tenggara.',
    'Beberapa mangaka terkenal karena gaya gambar mereka yang sangat detail.',
    'Anime musiman biasanya tayang tiap 3 bulan sekali mengikuti kalender musim di Jepang.',
    'Light novel sering jadi sumber cerita buat anime genre isekai dan fantasy.',
    'Beberapa anime punya lebih dari satu studio berbeda yang menggarap season berbeda.',
    'Karakter anime ikonik sering muncul di kolaborasi brand di luar animenya sendiri.',
    'Fans anime sering bikin komunitas diskusi teori tiap episode baru tayang.',
];

export const MOTIVASI_HARIAN = [
    'Nggak apa-apa kalau hari ini terasa berat. Besok kamu masih punya kesempatan buat coba lagi.',
    'Progres kecil tetap progres. Jangan remehin langkah kecil yang kamu ambil hari ini.',
    'Kamu nggak harus jadi sempurna buat pantas dihargai usahamu.',
    'Istirahat itu bukan tanda menyerah, tapi bagian dari proses buat lanjut lebih kuat.',
    'Fokus ke progres kamu sendiri, bukan ke kecepatan orang lain.',
    'Setiap hari yang kamu lewatin dengan usaha adalah investasi buat dirimu di masa depan.',
    'Kalau capek, istirahat. Tapi jangan berhenti.',
    'Kamu lebih kuat dari yang kamu kira, cuma kadang perlu waktu buat nyadarinnya.',
    'Nggak semua orang bakal ngerti perjuanganmu, dan itu nggak apa-apa.',
    'Yang penting bukan seberapa cepat kamu sampai, tapi seberapa konsisten kamu jalan.',
    'Rasa takut gagal itu wajar. Yang penting jangan biarkan itu berhentiin langkahmu.',
    'Hari ini mungkin susah, tapi itu bagian dari cerita perjuanganmu, bukan akhir dari segalanya.',
    'Jangan bandingin bab satu hidupmu sama bab dua puluh hidup orang lain.',
    'Setiap usaha kecil yang konsisten, lama-lama jadi perubahan besar.',
    'Kamu berhak bangga sama diri sendiri, sekecil apapun progresnya.',
    'Kegagalan itu bukan lawan dari sukses, tapi bagian dari proses menuju sukses.',
    'Percaya sama waktu. Nggak semua hasil kelihatan instan.',
    'Kamu nggak sendirian. Banyak orang juga lagi berjuang dengan cara mereka masing-masing.',
    'Jangan lupa istirahat cukup, tubuh dan pikiran sehat itu fondasi semua pencapaian.',
    'Kadang yang kamu butuhin cuma napas panjang dan mulai lagi pelan-pelan.',
    'Semua ahli pernah jadi pemula. Nggak ada yang instan.',
    'Kamu berkembang lebih banyak dari yang kamu sadari, cuma butuh waktu buat kelihatan hasilnya.',
    'Jangan takut mulai dari nol. Takutlah kalau kamu nggak pernah mulai sama sekali.',
    'Kekuatanmu hari ini adalah hasil dari semua hari sulit yang udah kamu lewatin.',
    'Nggak masalah kalau rencana berubah, yang penting arah tujuanmu tetap jelas.',
    'Setiap orang punya waktu masing-masing buat bersinar. Punyamu juga akan datang.',
    'Kamu boleh capek, tapi jangan lupa kenapa kamu mulai.',
    'Hidup nggak harus sempurna buat tetap layak disyukuri.',
    'Fokus sama apa yang bisa kamu kontrol, lepasin yang nggak bisa.',
    'Kamu udah berhasil lewatin seratus persen hari terburukmu sejauh ini. Itu prestasi.',
];

export const FAKTA_SERU = [
    'Madu adalah salah satu makanan yang nggak pernah basi kalau disimpan dengan benar.',
    'Jantung udang justru terletak di bagian kepalanya, bukan badan.',
    'Gurita punya tiga jantung dan darah berwarna biru.',
    'Bintang laut nggak punya otak, tapi tetap bisa mendeteksi cahaya dan makanan.',
    'Satu hari di planet Venus lebih lama dari satu tahun di planet itu sendiri.',
    'Suara guntur berasal dari udara yang memuai secara ekstrem gara-gara panas kilat.',
    'Bulu angsa dan bebek kedap air berkat minyak alami yang mereka hasilkan sendiri.',
    'Manusia berbagi sekitar 60% DNA yang sama dengan pisang.',
    'Gajah adalah salah satu hewan yang bisa mengenali dirinya sendiri di cermin.',
    'Hiu sudah ada di bumi lebih lama dari pohon, bahkan sebelum dinosaurus.',
    'Kelelawar adalah satu-satunya mamalia yang benar-benar bisa terbang, bukan sekadar melayang.',
    'Titik terdalam lautan Bumi ada di Palung Mariana.',
    'Lebah bisa mengenali wajah manusia dengan cara mengingat pola tertentu.',
    'Warna langit biru terjadi karena cahaya matahari dipantulkan partikel di atmosfer.',
    'Beruang kutub sebenarnya punya kulit berwarna hitam di balik bulunya yang putih.',
    'Otak manusia menggunakan sekitar 20% energi tubuh meski ukurannya cuma 2% berat badan.',
    'Jerapah cuma tidur sekitar 2 jam sehari, sering sambil berdiri.',
    'Cokelat awalnya dikonsumsi sebagai minuman pahit oleh peradaban kuno Amerika Tengah.',
    'Bunga matahari sebenarnya kumpulan ratusan bunga kecil dalam satu tangkai.',
    'Es batu di air asin mencair lebih lambat dibanding di air tawar.',
    'Ubur-ubur sudah ada di lautan bumi jauh sebelum dinosaurus muncul.',
    'Suara kita sendiri kedengaran beda di rekaman karena jalur getaran suara yang berbeda.',
    'Rata-rata orang menghabiskan sekitar sepertiga hidupnya buat tidur.',
    'Kucing punya lebih dari selusin cara mengeong, kebanyakan khusus ditujukan ke manusia.',
    'Petir bisa lebih panas dari permukaan matahari untuk sepersekian detik.',
    'Paus biru adalah hewan terbesar yang pernah hidup di Bumi.',
    'Semut nggak punya paru-paru, mereka bernapas lewat lubang kecil di tubuhnya.',
    'Air bisa berbentuk padat, cair, dan gas sekaligus dalam kondisi titik tripel.',
    'Beberapa jenis kura-kura bisa hidup lebih dari seratus tahun.',
    'Manusia adalah satu-satunya hewan yang diketahui bisa tersipu malu.',
    'Piramida Giza dibangun ribuan tahun sebelum mammoth berbulu benar-benar punah.',
    'Hidung manusia bisa mengingat sampai puluhan ribu aroma berbeda.',
    'Koala tidur sampai 20 jam sehari karena makanannya rendah energi dan sulit dicerna.',
    'Bulan perlahan menjauh dari Bumi setiap tahunnya, meski jaraknya sangat kecil.',
    'Kupu-kupu bisa merasakan rasa manis lewat kakinya, bukan mulutnya.',
    'Suara paus bisa terdengar hingga ratusan kilometer jauhnya di dalam air.',
    'Ada lebih banyak pohon di Bumi dibanding jumlah bintang di galaksi Bima Sakti.',
    'Sebagian besar oksigen di Bumi dihasilkan fitoplankton di lautan, bukan cuma dari hutan.',
    'Gigi manusia adalah satu-satunya bagian tubuh yang nggak bisa memperbaiki dirinya sendiri.',
    'Kuda nil bisa berlari lebih cepat dari manusia meski tubuhnya besar dan berat.',
];

export const KETAWA = [
    'Kenapa komputer sering masuk angin? Soalnya banyak windows-nya kebuka terus.',
    'Kenapa hantu nggak pernah bohong? Soalnya ketauan tembus pandang.',
    'Apa bedanya kamu sama Wi-Fi? Wi-Fi masih mau connect, kalau kamu susah didekati.',
    'Kenapa ikan nggak suka main kartu? Takut ketauan lagi mancing.',
    'Kenapa tukang parkir jago matematika? Soalnya tiap hari itung-itungan slot kosong.',
    'Kenapa semut nggak pernah sakit gigi? Soalnya rajin bawa makanan kecil-kecil.',
    'Apa makanan kesukaan hantu? Yang penting ada isinya, biar nggak kosongan.',
    'Kenapa kalender selalu populer? Soalnya punya banyak tanggal.',
    'Kenapa laptop gampang capek? Soalnya kerja terus tanpa cuti.',
    'Apa bedanya kopi sama masalah? Kopi bisa diselesaikan sambil santai, masalah kadang enggak.',
    'Kenapa kucing suka duduk di kardus? Soalnya lagi cari privasi ala pejabat.',
    'Kenapa baterai HP cepat habis pas lagi seru chat? Soalnya energinya kepake buat baper.',
    'Apa bedanya kamu sama koneksi internet? Sama-sama suka putus di saat penting.',
    'Kenapa tukang bakso nggak pernah kesepian? Soalnya selalu ada yang notice.',
    'Kenapa jam dinding nggak pernah telat? Soalnya kerjaannya emang muter aja terus.',
    'Kenapa awan nggak pernah cerita rahasia? Takut ketauan waktu ujan.',
    'Apa julukan kucing yang jago ngoding? Cat-developer.',
    'Kenapa nasi goreng jadi menu sejuta umat? Soalnya gampang disesuaikan sama selera.',
    'Kenapa lampu nggak pernah sombong? Soalnya sadar dia cuma nyala kalau ada yang nyalain.',
    'Apa bedanya kamu sama sinyal HP di pegunungan? Sama-sama suka ilang pas dibutuhin.',
    'Kenapa pensil nggak pernah stres? Soalnya ada penghapus buat mulai ulang.',
    'Kenapa kipas angin nggak pernah baper? Soalnya udah biasa muter-muter doang.',
    'Apa makanan favorit tukang parkir? Yang penting slot-nya pas.',
    'Kenapa kalkulator selalu dipercaya? Soalnya nggak pernah asal ngomong tanpa hitung dulu.',
    'Kenapa charger HP suka dicariin banget? Soalnya paling ngerti kalau baterai lagi lemah.',
    'Apa bedanya kamu sama alarm pagi? Sama-sama diabaikan lima menit pertama.',
    'Kenapa google maps sabar banget? Soalnya biasa nunjukin jalan meski sering diabaikan.',
    'Kenapa remote TV sering ilang? Soalnya emang jagoan sembunyi di rumah sendiri.',
    'Apa bedanya deadline sama kereta? Sama-sama nggak nungguin kamu siap.',
    'Kenapa emoji senyum paling sering dipakai? Soalnya gampang nutupin apa yang lagi dirasain.',
];

export const BERCANDA = [
    'Santai ya, nggak semua orang bisa se-unik kamu... untungnya.',
    'Kamu tuh kayak sinyal WiFi tetangga, keliatan tapi susah connect.',
    'Nggak apa telat mikir, yang penting sampe juga akhirnya.',
    'Kamu itu spesial, kayak captcha yang susah dibaca.',
    'Gaya kamu emang beda, kayak playlist acak yang nggak ketebak lanjutannya.',
    'Kamu kayak update aplikasi, dateng pas lagi nggak dibutuhin.',
    'Santuy aja, hidup emang nggak selalu sesuai FYP.',
    'Kamu unik banget, kayak charger yang nggak pernah cocok sama HP orang lain.',
    'Nggak semua rencana harus jalan mulus, kadang kayak loading 99% terus stuck.',
    'Kamu kayak iklan skip lima detik, keliatan random tapi tetep nempel di ingatan.',
    'Santai, semua orang pernah salah ketik nama di chat penting.',
    'Kamu tuh kayak baterai low tapi masih maksa buka banyak aplikasi.',
    'Gapapa telat bales chat, yang penting nggak di-read doang.',
    'Kamu kayak lagu yang diputer ulang terus padahal udah bosen, tapi tetep asik.',
    'Santuy, typo itu bukti kamu manusia biasa kok.',
    'Kamu kayak kuota internet, keliatan banyak tapi cepet abisnya.',
    'Nggak masalah plan berubah mendadak, hidup emang suka php.',
    'Kamu tuh kayak alarm snooze, diabaikan tapi tetep balik lagi.',
    'Santai aja, nggak semua meme related sama kamu, kadang doang.',
    'Kamu kayak koneksi 3G di gedung tinggi, ada usaha tapi hasilnya lemot.',
];

export const PUJIAN_SERU = [
    'Kamu punya cara ngomong yang bikin orang lain ngerasa didengerin.',
    'Effort kamu keliatan banget, bahkan di hal-hal kecil sekalipun.',
    'Kamu tipe orang yang bikin suasana jadi lebih enak cuma dengan hadir.',
    'Cara kamu mikir out of the box selalu bikin orang lain kepikiran juga.',
    'Kamu konsisten banget buat orang yang keliatan santai.',
    'Senyum kamu tuh jenis yang bikin orang lain ikut mood-nya jadi baikan.',
    'Kamu punya kesabaran yang jarang dimiliki orang kebanyakan.',
    'Cara kamu bantu orang lain tuh tulus banget, kelihatan nggak dibuat-buat.',
    'Kamu tuh tipe teman yang selalu diinget waktu orang butuh saran jujur.',
    'Semangat kamu buat belajar hal baru tuh nular ke orang sekitar.',
    'Kamu selalu bisa liat sisi positif dari situasi yang keliatannya susah.',
    'Kreativitas kamu keliatan banget di detail-detail kecil yang kamu bikin.',
    'Kamu tipe orang yang bikin orang lain ngerasa aman buat jadi diri sendiri.',
    'Rasa humor kamu pas banget, nggak berlebihan tapi selalu bikin ketawa.',
    'Kamu punya cara yang tenang buat hadepin masalah, itu jarang dimiliki orang.',
    'Progres kamu dari waktu ke waktu keliatan banget, kerja keras kamu terbayar.',
    'Kamu selalu jujur dengan cara yang tetap bikin orang lain nyaman.',
    'Cara kamu dengerin orang lain bikin mereka ngerasa dihargai.',
    'Kamu punya energi yang bikin tim jadi lebih solid.',
    'Kamu tuh bukti kalau usaha pelan-pelan tetap bisa hasilin sesuatu yang keren.',
];

export const PANTUN_SERU = [
    'Jalan-jalan ke Kota Blitar, jangan lupa mampir ke pasar. Kalau hidup ingin lancar, jangan lupa selalu sabar.',
    'Pergi memancing bawa jala, dapat ikan dua ekor. Kalau kerja penuh upaya, hasil manis pasti mengalir.',
    'Beli duku di pinggir jalan, jangan lupa beli manggis. Kalau rindu jangan dipendam, sapa saja lewat chat manis.',
    'Burung camar terbang tinggi, hinggap sejenak di dahan jati. Jangan pernah menyerah lagi, sukses milik yang gigih hati.',
    'Ke pasar membeli tomat, mampir sebentar beli terasi. Kalau kerja penuh semangat, hasilnya pasti memuaskan hati.',
    'Ke sawah menanam padi, jalan pulang lewat setapak. Jadilah teman yang baik hati, biar hidup terasa lebih hangat.',
    'Naik delman keliling kota, singgah sebentar beli es krim. Kalau kamu lagi capek dan lelah, istirahat dulu jangan dipaksain.',
    'Pohon jati tumbuh di ladang, buahnya jatuh satu per satu. Siapa yang sabar berjuang, hasilnya nanti pasti tertata bagus.',
    'Beli mangga di Indramayu, rasanya manis bikin ketagihan. Kalau kamu lagi ragu, coba dulu baru putuskan.',
    'Layang-layang terbang di angkasa, talinya panjang dimainkan anak-anak. Jangan takut mencoba hal baru, siapa tahu itu yang cocok banget.',
    'Pergi ke kebun memetik jambu, pulangnya lewat jalan berbatu. Kalau lagi susah jangan buru-buru, pelan-pelan juga sampai tujuan kamu.',
    'Ke laut mencari mutiara, ombaknya tenang di sore hari. Kalau hidup terasa berat rasanya, ingat kamu nggak sendiri kok jalani ini.',
    'Beli topi di pasar malam, warnanya cerah banyak pilihan. Kalau salah jangan lama dipendam, minta maaf itu bukan kekalahan.',
    'Kupu-kupu hinggap di bunga, sayapnya indah warna-warni. Jadilah orang yang selalu berusaha, biar hasilnya nanti manis sendiri.',
    'Ke gunung mendaki pelan-pelan, udaranya sejuk bikin tenang. Hidup memang penuh tantangan, tapi kamu pasti bisa menang.',
    'Beli rambutan di pinggir desa, kulitnya merah isinya manis. Kalau capek istirahat sebentar saja, biar besok bisa lebih semangat lagi.',
    'Pergi ke kota naik kereta, jendelanya lebar pemandangan indah. Semangat terus jangan pernah menyerah, tujuanmu nggak akan sia-sia.',
    'Menanam bunga di halaman rumah, warnanya cerah bikin hati riang. Jaga selalu hati yang ramah, biar hidup terasa lebih tenang.',
    'Beli es kelapa di siang bolong, segarnya bikin hilang dahaga. Kalau lelah boleh berhenti sejenak, asal jangan lupa jalan lagi nantinya.',
    'Layangan putus dibawa angin, terbang jauh entah ke mana. Jangan pernah takut buat mulai lagi, karena setiap akhir ada awal yang baru.',
];

export const WEJANGAN = [
    'Diam itu bukan kalah, kadang itu cara paling bijak buat jaga hubungan.',
    'Nggak semua hal harus dijelasin ke semua orang.',
    'Orang yang tenang biasanya udah lewatin badai yang nggak semua orang tau.',
    'Kesalahan itu guru paling jujur, walau kadang caranya nyakitin.',
    'Yang paling susah dimaafin sering kali diri sendiri.',
    'Nggak semua yang pergi harus dikejar. Ada yang emang harus dilepas.',
    'Waktu nggak pernah salah, kita aja yang kadang buru-buru.',
    'Belajar dari masa lalu, tapi jangan tinggal di sana.',
    'Kesederhanaan sering disalahartikan sebagai kekurangan, padahal itu kekuatan.',
    'Nggak semua pertanyaan butuh jawaban instan.',
    'Orang yang banyak diam belum tentu nggak punya pendapat, kadang dia cuma milih waktu yang tepat.',
    'Kedewasaan itu bukan soal umur, tapi soal cara ngadepin masalah.',
    'Kamu nggak wajib jelasin keputusanmu ke semua orang.',
    'Kadang yang kamu butuh cuma ngerti, bukan solusi.',
    'Semua hal butuh proses, termasuk buat berdamai sama diri sendiri.',
    'Nggak semua luka kelihatan, makanya jangan gampang nge-judge orang.',
    'Kepercayaan itu dibangun pelan-pelan, tapi bisa runtuh dalam sekejap.',
    'Kadang yang bikin capek bukan masalahnya, tapi mikirinnya kebanyakan.',
    'Belajar bilang tidak itu juga bagian dari menghargai diri sendiri.',
    'Hal terbaik yang bisa kamu kasih ke diri sendiri adalah waktu buat pulih.',
];

// Tebak-tebakan: { q: pertanyaan, a: jawaban } — dikirim sekaligus dalam satu balasan.
export const TEBAKAN = [
    { q: 'Kenapa lebah selalu berdengung waktu terbang?', a: 'Soalnya dia lupa liriknya, cuma inget nadanya doang!' },
    { q: 'Ada apel jatuh dari pohon tapi nggak ada yang denger suaranya. Kenapa?', a: 'Soalnya nggak ada orang di sekitar yang lagi natap ke arah sana!' },
    { q: 'Kenapa kalender selalu jadi favorit semua orang?', a: 'Soalnya harinya nggak pernah bohong, semua tanggal jujur adanya!' },
    { q: 'Binatang apa yang kalau jalan bawa rumah sendiri?', a: 'Siput! Praktis banget, nggak perlu bayar kontrakan.' },
    { q: 'Kenapa air laut asin?', a: 'Karena ikan-ikannya nggak pernah nangis di darat, jadi air matanya numpuk di laut!' },
    { q: 'Apa yang bertambah kalau dibagi terus?', a: 'Lubang! Semakin digali, semakin besar lubangnya.' },
    { q: 'Benda apa yang punya kepala dan ekor tapi nggak punya badan?', a: 'Koin!' },
    { q: 'Kenapa jam dinding nggak pernah capek?', a: 'Soalnya kerjaannya emang muter-muter aja, udah terbiasa.' },
    { q: 'Apa yang jalan tapi nggak pernah pindah tempat?', a: 'Jam! Jarumnya jalan terus tapi jamnya tetap nempel di dinding.' },
    { q: 'Binatang apa yang paling jujur soal ukuran tubuhnya?', a: 'Jerapah, lehernya aja nggak bisa bohong soal tinggi.' },
    { q: 'Kenapa payung selalu sedih pas musim kemarau?', a: 'Soalnya jarang dipake, jadi ngerasa kurang berguna.' },
    { q: 'Apa yang punya banyak gigi tapi nggak bisa gigit?', a: 'Sisir!' },
    { q: 'Benda apa yang makin dicuci makin kotor?', a: 'Air cucian!' },
    { q: 'Kenapa semut nggak pernah kesasar?', a: 'Soalnya mereka jalan rombongan sambil ninggalin jejak bau khusus.' },
    { q: 'Apa yang bisa keliling dunia tapi tetap di pojokan kamar?', a: 'Perangko di amplop surat!' },
    { q: 'Kenapa bulan nggak pernah kepanasan walau deket matahari?', a: 'Soalnya dia cuma numpang mantul cahaya, nggak nyerap panasnya.' },
    { q: 'Binatang apa yang bawa tas kemana-mana?', a: 'Kanguru, di badannya sendiri ada kantongnya!' },
    { q: 'Apa yang tambah lama tambah pendek?', a: 'Lilin yang lagi nyala.' },
    { q: 'Kenapa pisang bentuknya melengkung?', a: 'Soalnya tumbuh mengejar sinar matahari, jadi melengkung ke atas.' },
    { q: 'Apa yang bisa penuh tapi nggak pernah berat?', a: 'Pikiran yang lagi banyak beban!' },
];
